builtin_interfaces/Time stamp

string interceptor_id

bool connected
bool armed
bool offboard_enabled
bool failsafe

uint8 nav_state
uint8 arming_state

float32 battery_remaining
float32 battery_voltage_v

float64 latitude_deg
float64 longitude_deg
float32 altitude_m

float32 local_x_m
float32 local_y_m
float32 local_z_m

float32 velocity_x_mps
float32 velocity_y_mps
float32 velocity_z_mps

float32 heading_rad
